### ISSUE TITLE
Just blank page :-(

### ISSUE THREAD

**Issue by Ziggizag** [Tommertom/svelte-ionic-blank-demo#1]
Hi!

Actually, I am a newbie to Svelte, but I wanted to try...

So - the package manager complained a lot for missing versions, but finally, it completed. I've got this in the console after connection, but it seems it's fine.

`VITE v3.0.0  ready in 465 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
6:44:34 PM [vite-plugin-svelte] /home/ziggi/public_html/svelte/node_modules/@roxi/routify/lib/runtime/Instance/Node.svelte:16:8 <Component/> will not be reactive if Component changes. Use <svelte:component this={Component}/> if you want this reactivity.`

But the case is... In a browser I only get completely blank page with "index.html" source code.

JavaScript console complains:

Uncaught SyntaxError: import not found: PopoverOptions

This is ugly :-(

**Comment by Ziggizag** [comment]
It seems the error comes from this:

![image](https://user-images.githubusercontent.com/2280036/180491349-d5b23e43-f228-4497-a45a-af35461b3ff4.png)

**Comment by Ziggizag** [comment]
When I commented out PopoverOptions, I've got another error:

`Uncaught SyntaxError: import not found: ModalOptions`

When I commented out this, there was the next one:

`Uncaught SyntaxError: import not found: IonicConfig`

This is hardly a friendly scaffold :/

**Comment by Tommertom** [comment]
Hey @Ziggizag  - sorry about this

Let me look into it later today

Thx for reporting

**Comment by Tommertom** [comment]
Ok so I just did a brief download and npm install and stuff fails

I think it is because of a vite upgrade or so

I am running vite v2.9.13. The install asks for 2.9.9 or so and you are working on 3.0.0.  So I need to fix whatever the new vite is reporting

Problem now - I have poor wifi so not able to resolve immediately - likely tomorrow

I could ask you to check the other starters but I dont think that will help

**Comment by Ziggizag** [comment]
OK - not in a hurry - just a private "catch new skill" attempt :-D

Just - let me know when you manage to fix it, if feasible. I would appreciate it!

Have a nice holliday!

**Comment by Tommertom** [comment]
Thx! 

Meanwhile - this works? Best is to popout the output

https://codesandbox.io/s/github/Tommertom/svelte-ionic-blank-demo

**Comment by Ziggizag** [comment]
It looks like it's working:
![image](https://user-images.githubusercontent.com/2280036/180497822-aae2224d-59b6-4fbd-b2a7-d3ff4e2e3785.png)

**Comment by Ziggizag** [comment]
Yeap - problem solved. Thank you!
![image](https://user-images.githubusercontent.com/2280036/180498252-d32d9948-2ddf-4ebc-9dd7-13dbf9c07399.png)

**Comment by Tommertom** [comment]
Just to check - working in the codesandbox only or also when doing the clone and local install?

**Comment by Ziggizag** [comment]
@Tommertom You can see on the screenshot above: localhost:3000 :-)

It's all fine!

**Comment by Ziggizag** [comment]
@Tommertom 

I reopen. When recreating the project, I get this:

![image](https://user-images.githubusercontent.com/2280036/180582575-53429110-9505-4d3d-9d2a-aa550db11ec5.png)

Any idea?

**Comment by Tommertom** [comment]
Can you post the package.json of the project in that directory.

Need to check against what I have

**Comment by Ziggizag** [comment]
Sure,

Here you are:

`{
  "name": "ionicsvelte",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build && vite build --ssr",
    "build:client": "vite build",
    "build:server": "vite build  --ssr",
    "preview": "vite preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "routes": "routify"
  },
  "devDependencies": {
    "@rollup/plugin-alias": "^3.1.9",
    "@roxi/routify": "^3.0.0-next.93",
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.30",
    "@tsconfig/svelte": "^2.0.1",
    "sass": "^1.52.2",
    "spank": "^2.0.0-5",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.7",
    "svelte-preprocess": "^4.9.8",
    "tslib": "^2.3.1",
    "typescript": "^4.5.4",
    "vite": "^2.9.9",
    "vite-plugin-pwa": "^0.12.0"
  },
  "dependencies": {
    "@ionic/core": "^6.1.8"
  },
  "routify": {
    "pages": "./src/routes"
  }
}`

**Comment by Tommertom** [comment]
Ok thx

npm i vite@3.0.2 solved this for me

If you could check?

I will be updating package.json s for all starters later

There are more dependencies that can be updated

**Comment by Ziggizag** [comment]
Well, it seems it is working now. Thanks!

**Comment by Ziggizag** [comment]
I only added:

"@vitejs/plugin-basic-ssl": "^0.1.1"

To support SSL on Vite server. For whatever reason after the last update it has lost default certs :/

**Comment by Tommertom** [comment]
yes, it is mentioned in the changelog that ssl now requires explicit action by the developer

**Comment by Ziggizag** [comment]
Hmm - it's hard to find any changelog here, actually (or I am short seeing).

Anyway - I can tell you - I am an experienced PHP backend developer. I developed and manage a commercial app with ~200 thousand end users. I have missed angular / react / vou days and now I see it's svelte a new hype... Damn - the entry barrier is high!

First of all - it seems everybody in this community is fluent in a myriad of tools and libraries I have never heard about. The technology stack is gargantuan. Most of the sample projects never work! There is always some "minor" obstacle like missing dependency, wrong version, some typo in code, some instruction wrongdoing...

And finally, when after spending days getting the basic project started - I realize Svelte is an uneasy beast!

There is no good practical tutorial! How is the page layout constructed? How to position elements? Even to get them rendered!

I try to implement basic navigation - I can see the router constructed default routes to tabs, but - no output. I try to "copy-paste" from your "My Starter Demo" into "Blank Page Demo" and I cannot "catch" where is the rendering missing :/

If you could recommend some good entry-level tutorials, I would appreciate it. I mean - from layout maquette to working site. It is not about fancy at the moment, Dynamic integration with PHP-backend will come later on. But just to get the idea of how to use page layouts, how to apply different layouts to different pages, how to enable/disable widgets, how to navigate... etc.

**Comment by Tommertom** [comment]
Hi,

here is the change managed - not a changelog  :) - https://vitejs.dev/guide/migration.html

The hell we are all in is that APIs change with the blink of an eye. So tutorials get outdated rapidly.

Angular is very opinionated so that helps beginners - even though there is still a steep learning curve
React has a huge community but requires you to make many choices yourself on app architecture
Vue sits in the middle and is gaining ground and has a good following
Svelte is new to the party - maybe even a bit too late. With SvelteKit trying to push a new paradigm combined client and server side rendering - to me a very new thing and even more complex animal


To learn basics of svelte -  I like the tutorial  - https://svelte.dev/tutorial/basics. And then reading through the docs.

The routing is file-based as you saw. Ionic Tabs is a bit of strange animal to that extend. It is not a route from the router, but a component loaded, wheren the IonTabs translates the route to component loading. 

This is because integrating Ionic with Svelte is actually not that easy. A number of Ionic components require tight integration with the router  - tabs, page, backbutton, nav.... and this is not even fully finished - with some workarounds.

And some things are likely going to be almost impossible due to the webcomponents structure and the way Svelte (does not) like to fully embrace web components.

The demos use Routify as router - https://v3.ci.routify.dev/docs# . I hope they will be updating their docs as they have everything but in very minimalistic way

I am happy to help along the way. I can learn from what you encounter and maybe ease the curve for others - although, some still requires a bit biting the dust by people getting onboard.

I do like the svelte-ionic combination to prototype very rapidly. I am coming from an Angular background and svelte is indeed a beast - but mainly because of it sheer simplicity and power.

**Comment by Ziggizag** [comment]
Yeap,

Documentation minimalism is a bit confusing in the node.js community. It is similar to Unix-world docs. Very high abstraction level based on the optimistic outlook of the end-user background :-D

Most probably ionic is a bit too hard for my entry level at the moment. It seems I need to start from scratch.

Anyway - svelte.dev tutorial is fine to get the basic idea of what are Svelte components and how they do communicate with each other, but it is not really helpful in terms of practical design. It seems all these tutorials go through the singular "widget". They miss completely the idea of layouts, which are the basics of every practical website...

In the case of a "normal" page, I use a layout file, and I fill it with rendered content. Often using widget classes, so it is super-easy. Layout is like a styled slot for the final content. You can browse through the Svelte tutorial, and notice they even do not say a word about layouts :/

**Comment by Tommertom** [comment]
https://www.youtube.com/watch?v=prsXVk1fdW4

Maybe this helps a bit, but svelte now might be a bit too low level?

https://github.com/TheComputerM/awesome-svelte

**Comment by Ziggizag** [comment]
Thank you!

The video presentation by Simon is indeed excellent!
